[workspace]
members = [ "coreutils/cat", "coreutils/cp",
    "coreutils/echo",
    "coreutils/ls", "coreutils/mkdir", "coreutils/mv",
    "coreutils/pwd", "coreutils/rm",
    "shell"
]
resolver = "3"
